global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spark'
    static_configs:
      - targets: ['localhost:4040']
  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9092']
  - job_name: 'system'
    static_configs:
      - targets: ['localhost:9100']
